services:
  postgres:
    container_name: postgres
    image: postgres:17.2
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - '5432:5432'
    network_mode: 'host'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: feature_flags

  app:
    container_name: feature-flags
    image: server-app
    working_dir: /app
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '8080:8080'
    env_file:
      - .env
    environment:
      - DATABASE_URI
      - DATABASE_PASSWORD
    depends_on:
      - postgres
