services:
  postgres:
    container_name: postgres
    image: postgres:17.2
    restart: unless-stopped
    env_file: .env
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_DB:${POSTGRES_NAME}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 5

  # app:
  #   container_name: feature-flags
  #   image: server-app
  #   working_dir: /app
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   ports:
  #     - '8080:8080'
  #   env_file:
  #     - .env
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   restart: always
  #   volumes:
  #     - ./:/app
  #
volumes:
  database:
