// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Env struct {
	ID         int32
	Name       pgtype.Text
	OriginHost pgtype.Text
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type FeatureFlag struct {
	ID        int32
	Name      pgtype.Text
	Value     pgtype.Bool
	EnvID     pgtype.Int4
	GroupID   pgtype.Int4
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Group struct {
	ID        int32
	Name      pgtype.Text
	EnvID     pgtype.Int4
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
