// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnv = `-- name: CreateEnv :one
INSERT INTO env (name, origin_host) VALUES ($1, $2) RETURNING id, name, origin_host, created_at, updated_at
`

type CreateEnvParams struct {
	Name       pgtype.Text
	OriginHost pgtype.Text
}

func (q *Queries) CreateEnv(ctx context.Context, arg CreateEnvParams) (Env, error) {
	row := q.db.QueryRow(ctx, createEnv, arg.Name, arg.OriginHost)
	var i Env
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OriginHost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFF = `-- name: CreateFF :one
INSERT INTO feature_flags (name, env_id) VALUES ($1, $2) RETURNING id, name, value, env_id, group_id, created_at, updated_at
`

type CreateFFParams struct {
	Name  pgtype.Text
	EnvID pgtype.Int4
}

func (q *Queries) CreateFF(ctx context.Context, arg CreateFFParams) (FeatureFlag, error) {
	row := q.db.QueryRow(ctx, createFF, arg.Name, arg.EnvID)
	var i FeatureFlag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.EnvID,
		&i.GroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, env_id) VALUES ($1, $2) RETURNING id, name, env_id, created_at, updated_at
`

type CreateGroupParams struct {
	Name  pgtype.Text
	EnvID pgtype.Int4
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.Name, arg.EnvID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EnvID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEnv = `-- name: DeleteEnv :exec
DELETE FROM env WHERE id = $1
`

func (q *Queries) DeleteEnv(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteEnv, id)
	return err
}

const deleteFF = `-- name: DeleteFF :exec
DELETE FROM feature_flags WHERE id = $1
`

func (q *Queries) DeleteFF(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteFF, id)
	return err
}

const deleteFFsByEnvId = `-- name: DeleteFFsByEnvId :exec
DELETE FROM feature_flags WHERE env_id = $1
`

func (q *Queries) DeleteFFsByEnvId(ctx context.Context, envID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteFFsByEnvId, envID)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id=$1
`

func (q *Queries) DeleteGroup(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const getEnv = `-- name: GetEnv :one
SELECT id, name, origin_host, created_at, updated_at FROM env WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEnv(ctx context.Context, id int32) (Env, error) {
	row := q.db.QueryRow(ctx, getEnv, id)
	var i Env
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OriginHost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvAll = `-- name: GetEnvAll :many
SELECT id, name, origin_host, created_at, updated_at FROM env
`

func (q *Queries) GetEnvAll(ctx context.Context) ([]Env, error) {
	rows, err := q.db.Query(ctx, getEnvAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Env
	for rows.Next() {
		var i Env
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OriginHost,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnvCount = `-- name: GetEnvCount :one
SELECT COUNT(*) FROM env
`

func (q *Queries) GetEnvCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getEnvCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFF = `-- name: GetFF :one
SELECT id, name, value, env_id, group_id, created_at, updated_at FROM feature_flags WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFF(ctx context.Context, id int32) (FeatureFlag, error) {
	row := q.db.QueryRow(ctx, getFF, id)
	var i FeatureFlag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.EnvID,
		&i.GroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFFAll = `-- name: GetFFAll :many
SELECT id, name, value, env_id, group_id, created_at, updated_at FROM feature_flags
`

func (q *Queries) GetFFAll(ctx context.Context) ([]FeatureFlag, error) {
	rows, err := q.db.Query(ctx, getFFAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeatureFlag
	for rows.Next() {
		var i FeatureFlag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Value,
			&i.EnvID,
			&i.GroupID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFFByEnvId = `-- name: GetFFByEnvId :many
SELECT id, name, value, env_id, group_id, created_at, updated_at FROM feature_flags WHERE env_id = $1
`

func (q *Queries) GetFFByEnvId(ctx context.Context, envID pgtype.Int4) ([]FeatureFlag, error) {
	rows, err := q.db.Query(ctx, getFFByEnvId, envID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeatureFlag
	for rows.Next() {
		var i FeatureFlag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Value,
			&i.EnvID,
			&i.GroupID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFFByName = `-- name: GetFFByName :many
SELECT id, name, value, env_id, group_id, created_at, updated_at FROM feature_flags WHERE name = $1
`

func (q *Queries) GetFFByName(ctx context.Context, name pgtype.Text) ([]FeatureFlag, error) {
	rows, err := q.db.Query(ctx, getFFByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeatureFlag
	for rows.Next() {
		var i FeatureFlag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Value,
			&i.EnvID,
			&i.GroupID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupsAll = `-- name: GetGroupsAll :many
SELECT id, name, env_id, created_at, updated_at FROM groups
`

func (q *Queries) GetGroupsAll(ctx context.Context) ([]Group, error) {
	rows, err := q.db.Query(ctx, getGroupsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EnvID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOne = `-- name: GetOne :one
SELECT id, name, env_id, created_at, updated_at FROM groups WHERE id = $1
`

func (q *Queries) GetOne(ctx context.Context, id int32) (Group, error) {
	row := q.db.QueryRow(ctx, getOne, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EnvID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEnv = `-- name: UpdateEnv :exec
UPDATE env set name = $2, origin_host = $3 WHERE id = $1
`

type UpdateEnvParams struct {
	ID         int32
	Name       pgtype.Text
	OriginHost pgtype.Text
}

func (q *Queries) UpdateEnv(ctx context.Context, arg UpdateEnvParams) error {
	_, err := q.db.Exec(ctx, updateEnv, arg.ID, arg.Name, arg.OriginHost)
	return err
}

const updateFF = `-- name: UpdateFF :exec
UPDATE feature_flags set value = $2 WHERE id = $1
`

type UpdateFFParams struct {
	ID    int32
	Value pgtype.Bool
}

func (q *Queries) UpdateFF(ctx context.Context, arg UpdateFFParams) error {
	_, err := q.db.Exec(ctx, updateFF, arg.ID, arg.Value)
	return err
}

const updateFFName = `-- name: UpdateFFName :exec
UPDATE feature_flags set name = $2 WHERE name = $1
`

type UpdateFFNameParams struct {
	Name   pgtype.Text
	Name_2 pgtype.Text
}

func (q *Queries) UpdateFFName(ctx context.Context, arg UpdateFFNameParams) error {
	_, err := q.db.Exec(ctx, updateFFName, arg.Name, arg.Name_2)
	return err
}

const updateGroup = `-- name: UpdateGroup :exec
UPDATE groups set name=$1 WHERE name=$2
`

type UpdateGroupParams struct {
	Name   pgtype.Text
	Name_2 pgtype.Text
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) error {
	_, err := q.db.Exec(ctx, updateGroup, arg.Name, arg.Name_2)
	return err
}
